from flask import Flask, request, render_template_string
import pickle
import pandas as pd

app = Flask(__name__)

# Load model
with open("random_forest_model.pkl", "rb") as f:
    clf_rf = pickle.load(f)

    print("Model loaded successfully")


    HTML_PAGE = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Random Forest Prediction</title>
            <style>
                    body {
                                font-family: Arial;
                                            margin: 40px;
                                                    }

                                                            button {
                                                                        padding: 10px 20px;
                                                                                    font-size: 16px;
                                                                                                cursor: pointer;
                                                                                                        }

                                                                                                                input {
                                                                                                                            margin-bottom: 20px;
                                                                                                                                    }

                                                                                                                                            table {
                                                                                                                                                        border-collapse: collapse;
                                                                                                                                                                    margin-top: 20px;
                                                                                                                                                                            }

                                                                                                                                                                                    th, td {
                                                                                                                                                                                                border: 1px solid #ddd;
                                                                                                                                                                                                            padding: 10px;
                                                                                                                                                                                                                        text-align: center;
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                        th {
                                                                                                                                                                                                                                                    background: #f4f4f4;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                                </head>
                                                                                                                                                                                                                                                                <body>

                                                                                                                                                                                                                                                                <h1>Random Forest Prediction</h1>

                                                                                                                                                                                                                                                                <form method="POST" enctype="multipart/form-data">
                                                                                                                                                                                                                                                                    <label>Upload Test CSV File:</label><br><br>

                                                                                                                                                                                                                                                                        <input type="file" name="test_file" required><br>

                                                                                                                                                                                                                                                                            <button type="submit">
                                                                                                                                                                                                                                                                                    Predict
                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                        </form>

                                                                                                                                                                                                                                                                                        {% if predictions %}
                                                                                                                                                                                                                                                                                        <h2>Predictions</h2>

                                                                                                                                                                                                                                                                                        <table>
                                                                                                                                                                                                                                                                                            <tr>
                                                                                                                                                                                                                                                                                                    <th>Row</th>
                                                                                                                                                                                                                                                                                                            <th>Prediction</th>
                                                                                                                                                                                                                                                                                                                    <th>Label</th>
                                                                                                                                                                                                                                                                                                                        </tr>

                                                                                                                                                                                                                                                                                                                            {% for pred in predictions %}
                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                        <td>{{ loop.index }}</td>
                                                                                                                                                                                                                                                                                                                                                <td>{{ pred }}</td>
                                                                                                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                                                                                                    {% if pred == 1 %}
                                                                                                                                                                                                                                                                                                                                                                                    Anomaly
                                                                                                                                                                                                                                                                                                                                                                                                {% else %}
                                                                                                                                                                                                                                                                                                                                                                                                                Nominal
                                                                                                                                                                                                                                                                                                                                                                                                                            {% endif %}
                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                            {% endfor %}
                                                                                                                                                                                                                                                                                                                                                                                                                                            </table>

                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            Predictions saved as <b>predictions.csv</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            {% endif %}

                                                                                                                                                                                                                                                                                                                                                                                                                                            {% if error %}
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style="color:red;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                {{ error }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                {% endif %}

                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                """


                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route("/", methods=["GET", "POST"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                def home():
                                                                                                                                                                                                                                                                                                                                                                                                                                                    predictions = None
                                                                                                                                                                                                                                                                                                                                                                                                                                                        error = None

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if request.method == "POST":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                file = request.files["test_file"]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Read uploaded CSV
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        X_test = pd.read_csv(file)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Save uploaded test file
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                X_test.to_csv("X_test.csv", index=False)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Predict
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        preds = clf_rf.predict(X_test)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Save predictions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pred_df = pd.DataFrame({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "prediction": preds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pred_df.to_csv(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "predictions.csv",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        index=False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                predictions = preds.tolist()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    error = str(e)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return render_template_string(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                HTML_PAGE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        predictions=predictions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                error=error
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        import os

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            port = int(os.environ.get("PORT", 8080))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        host="0.0.0.0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                port=port
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
